### ISSUE TITLE
crime: karma, combat stats, Charisma, Hack, and money per minute

### ISSUE THREAD

**Issue by quacksouls** [quacksouls/bitburner#8]
Similar to #91, but we exclude the Intelligence stat.

- [x] A save file where we have destroyed BN1.3 (Genesis) and BN4.3 (Singularity).  We need access to the Singularity API.
- [x] A script to calculate the following per minute for each crime: karma, combat stats, Charisma, Hack, and money.
- [x] Data on the amount of these per minute for each crime: karma, combat stats, Charisma, Hack, and money.

**Comment by quacksouls** [comment]
Done.  See
https://github.com/quacksouls/bitburner/tree/main/data/crime

**Comment by awfln** [comment]
this was useful!
